// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVDX4EJcG9n4nHs0458AkfEJqRTXJ1k5E',
    appId: '1:828871679843:web:215d239a9ba9ba36723d56',
    messagingSenderId: '828871679843',
    projectId: 'groupchat-4f1ef',
    authDomain: 'groupchat-4f1ef.firebaseapp.com',
    storageBucket: 'groupchat-4f1ef.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_0ErTj7jREsG7MlNIe5YPnhCJbGLMv6E',
    appId: '1:828871679843:android:7f5769e04a5b9f90723d56',
    messagingSenderId: '828871679843',
    projectId: 'groupchat-4f1ef',
    storageBucket: 'groupchat-4f1ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb6mGOPqAn8gMF6Zv1OHc-i8vkZllCvdw',
    appId: '1:828871679843:ios:e504e2660ab422bc723d56',
    messagingSenderId: '828871679843',
    projectId: 'groupchat-4f1ef',
    storageBucket: 'groupchat-4f1ef.appspot.com',
    iosBundleId: 'com.example.groupchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAb6mGOPqAn8gMF6Zv1OHc-i8vkZllCvdw',
    appId: '1:828871679843:ios:20ff3c4b48b71dce723d56',
    messagingSenderId: '828871679843',
    projectId: 'groupchat-4f1ef',
    storageBucket: 'groupchat-4f1ef.appspot.com',
    iosBundleId: 'com.example.groupchat.RunnerTests',
  );
}
